
name: 自动抓取每日微博热搜并生成词云图

on:
  schedule:
  - cron: "0 0/3 * * *"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Renew
      run: python3 weibo-hotrank.py

    - name: Commit and push
      run: |
        git diff
        git config --global user.email "626522796@qq.com"
        git config --global user.name "暗号"
        git add .
        git commit -am "自动抓取每日微博热搜并生成词云图"
        git push
