
name: 自动更新 README.md 文件

on:
  schedule:
  - cron: "0/10 5,6 * * *"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Renew
      run: python3 update-readme.py

    - name: Commit and push
      run: |
        git diff
        git config --global user.email "626522796@qq.com"
        git config --global user.name "暗号"
        git commit -am "自动更新 README.md 文件"
        git push
